enum Block {
    BORDER = 0,
    AIR,
    GROUND,
    PLAYER,
    FINISH,
    LAVA,
    SPRING,
    CHECKPOINT,
    STAR,
    LEFT,
    RIGHT,
    GRAVITY,

    HEXAGON,
    HEXAGON_LOCK,
    HEXAGON_UNLOCK,
    HEXAGON_IN,
    HEXAGON_IN_LOCK,
    HEXAGON_OUT,
    HEXAGON_OUT_LOCK,
    TRIANGLE,
    TRIANGLE_LOCK,
    TRIANGLE_UNLOCK,
    TRIANGLE_IN,
    TRIANGLE_IN_LOCK,
    TRIANGLE_OUT,
    TRIANGLE_OUT_LOCK,
    CIRCLE,
    CIRCLE_LOCK,
    CIRCLE_UNLOCK,
    CIRCLE_IN,
    CIRCLE_IN_LOCK,
    CIRCLE_OUT,
    CIRCLE_OUT_LOCK,
    SQUARE,
    SQUARE_LOCK,
    SQUARE_UNLOCK,
    SQUARE_IN,
    SQUARE_IN_LOCK,
    SQUARE_OUT,
    SQUARE_OUT_LOCK,
    
    STAR_LOCK,
    STAR_UNLOCK
}

const blockCodes: {[key: string]: string | number} = {
    air: 0,
    border: 'B',
    ground: 'G',
    player: 'P',
    finish: 'F',
    lava: 'L',
    spring: 'S',
    checkpoint: 'C',
    star: '*',
    left: '<',
    right: '>',
    gravity: 'GV',

    hexagon: 'kH',
    hexagon_lock: 'kHl',
    hexagon_unlock: 'kHu',
    hexagon_in: 'kHi',
    hexagon_out: 'kHo',
    hexagon_in_lock: 'kHI',
    hexagon_out_lock: 'kHO',
    
    triangle: 'kT',
    triangle_lock: 'kTl',
    triangle_unlock: 'kTu',
    triangle_in: 'kTi',
    triangle_out: 'kTo',
    triangle_in_lock: 'kTI',
    triangle_out_lock: 'kTO',

    circle: 'kC',
    circle_lock: 'kCl',
    circle_unlock: 'kCu',
    circle_in: 'kCi',
    circle_out: 'kCo',
    circle_in_lock: 'kCI',
    circle_out_lock: 'kCO',
    
    square: 'kS',
    square_lock: 'kSl',
    square_unlock: 'ksu',
    square_in: 'kSi',
    square_out: 'kSo',
    square_in_lock: 'kSI',
    square_out_lock: 'kSO',

    star_lock: 'k*l',
    star_unlock: 'k*u'
}

const blockTable: {[key: string]: Block} = {
    air: Block.AIR,
    border: Block.BORDER,
    ground: Block.GROUND,
    player: Block.PLAYER,
    finish: Block.FINISH,
    lava: Block.LAVA,
    spring: Block.SPRING,
    checkpoint: Block.CHECKPOINT,
    star: Block.STAR,
    left: Block.LEFT,
    right: Block.RIGHT,
    gravity: Block.GRAVITY,

    hexagon: Block.HEXAGON,
    hexagon_lock: Block.HEXAGON_LOCK,
    hexagon_unlock: Block.HEXAGON_UNLOCK,
    hexagon_in: Block.HEXAGON_IN,
    hexagon_out: Block.HEXAGON_OUT,
    hexagon_in_lock: Block.HEXAGON_IN_LOCK,
    hexagon_out_lock: Block.HEXAGON_OUT_LOCK,
    triangle: Block.TRIANGLE,
    triangle_lock: Block.TRIANGLE_LOCK,
    triangle_unlock: Block.TRIANGLE_UNLOCK,
    triangle_in: Block.TRIANGLE_IN,
    triangle_out: Block.TRIANGLE_OUT,
    triangle_in_lock: Block.TRIANGLE_IN_LOCK,
    triangle_out_lock: Block.TRIANGLE_OUT_LOCK,
    circle: Block.CIRCLE,
    circle_lock: Block.CIRCLE_LOCK,
    circle_unlock: Block.CIRCLE_UNLOCK,
    circle_in: Block.CIRCLE_IN,
    circle_out: Block.CIRCLE_OUT,
    circle_in_lock: Block.CIRCLE_IN_LOCK,
    circle_out_lock: Block.CIRCLE_OUT_LOCK,
    square: Block.SQUARE,
    square_lock: Block.SQUARE_LOCK,
    square_unlock: Block.SQUARE_UNLOCK,
    square_in: Block.SQUARE_IN,
    square_out: Block.SQUARE_OUT,
    square_in_lock: Block.SQUARE_IN_LOCK,
    square_out_lock: Block.SQUARE_OUT_LOCK,

    star_lock: Block.STAR_LOCK,
    star_unlock: Block.STAR_UNLOCK,
};

const COLLIDABLE = [
    Block.BORDER,
    Block.GROUND,
    Block.GRAVITY,
    
    Block.HEXAGON_LOCK,
    Block.TRIANGLE_LOCK,
    Block.CIRCLE_LOCK,
    Block.SQUARE_LOCK,
    Block.STAR_LOCK
];

const COLLECTIBLE = [
    Block.STAR,
    Block.HEXAGON,
    Block.TRIANGLE,
    Block.CIRCLE,
    Block.SQUARE
];

export {
    Block as default,
    blockTable,
    blockCodes,
    COLLIDABLE,
    COLLECTIBLE
};